### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by HaydnChen** [sconxu/react-native-checkbox#28]
> SyntaxError: /node_modules/react-native-checkbox/checkbox.js: Unexp
ected token (31:21)
>   29 |       checked: false,
>   30 |       checkedImage: './cb_enabled.png',
> > 31 |       uncheckedImage './cb_disabled.png',
>      |                      ^
>   32 |     }
>   33 |   },
>   34 |

**Comment by rajkissu** [comment]
#27 should fix this. @sconxu ^

**Comment by r0b1n** [comment]
It is not funny, but damn, this component still broken in `npm`.
@sconxu don't you perform even a single run to test it before publishing?

**Comment by bogdancarmanus** [comment]
@r0b1n i've published a fixed version in npm. the component should work now

**Comment by r0b1n** [comment]
@bogdancarmanus thank you!
